# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Learning - Prototype of Ingress-Nginx, Cert-Manager, Pekko-Http
email: tsnyder@contactoffice.com
name: "Tim Snyder"
url: "https://t-snyder.github.io/ingress-nginx-test/"
doc_name: "Steps for Deploying the Prototype" 
description: >- # this means to ignore newlines until "baseurl:"
  The purpose of the prototype project is to demonstrate the configuration and use of 
  ingress-nginx, and then increasing complexity with Cert-Manager and Pekko-Http within 
  the minikube environment. The tests include http and https terminated at the ingress 
  controller. Cert-manager is used to manage self-signed certificates for the TLS.
doc_url: "/_pages/README.md"
github_username:  t-snyder
minimal_mistakes_skin: aqua
#minimal_mistakes_skin: "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

#atom_feed:
#  hide: true
  
# Build settings
#theme: minima
markdown: kramdown
remote_theme: "t-snyder/minimal-mistakes"
#remote_theme: "mmistakes/minimal-mistakes@4.26.2"

# Outputting
#permalink: /:categories/:title/
#paginate: 5 # amount of posts to show
#paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
locale: "en-US"

include:
  - _pages

plugins:
  - jekyll-remote-theme
#  - jekyll-paginate
  - jekyll-sitemap
#  - jekyll-gist
#  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Tim Snyder"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "My bio is here."
  location : "At the Beach in Kenya"
  links:
    - label: "LinkedIn Profile"
#      icon: "/assets/icons/linked.png"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/tim-snyder-a3756/"
    - label: "GitHub Repo"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/t-snyder/"
 
footer:
  links:
    - label: "LinkedIn"
      icon: "/assets/icons/linked.png"
      url: "https://linkedin.com/in/tim-snyder-a3756"
    - label: "GitHub"
      icon: "/assets/icons/github.png"
      url: "https://github.com/t-snyder"
 
defaults:
  # _posts
#  - scope:
#      path: ""
#      type: posts
#    values:
#      layout: double
#      author_profile: true
#      read_time: true
#      comments: true
#      share: true
#      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: readme
      author_profile: true

#category_archive:
#  type: liquid
#  path: /categories/
#tag_archive:
#  type: liquid
#  path: /tags/  

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
